apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-registration
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: course-registration
    spec:
      containers:
        - name: app
          image: 582797602058.dkr.ecr.ap-northeast-2.amazonaws.com/course-registration-dev:v0.0.4
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8081

          envFrom:
            - configMapRef:
                name: course-registration-config
            - secretRef:
                name: course-registration-secret

          env:
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management # ★ http → management
            failureThreshold: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management # ★ http → management
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: management # ★ http → management
            periodSeconds: 5
            failureThreshold: 3
