apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: course-registration

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: course-registration
      app.kubernetes.io/part-of: course-registration-system
    includeSelectors: false
