apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: course-registration-tgc
spec:
  targetReference:
    name: course-registration
  defaultConfiguration:
    targetType: ip
    protocol: HTTP
    healthCheckConfig:
      healthCheckPath: /actuator/health
      healthCheckProtocol: HTTP
      healthCheckPort: "8081" # ★ 추가 (문자열! 따옴표 필수)
      matcher:
        httpCode: "200"
